version: '3.4'

volumes:
  mosquitto-data:
  mosquitto-logs:
  minecraft-logs:

services:
  minecraft-server:
    image: itzg/minecraft-bedrock-server
    container_name: minecraft-server
    environment:
      EULA: ${MC_EULA-TRUE}
      GAMEMODE: ${MC_GAMEMODE-creative}
      SERVER_NAME: ${MC_SERVER_NAME-YOUR_SERVER}
      ALLOW_CHEATS: ${MC_ALLOW_CHEATS-true}
      # ALLOW_LIST_USERS: "user1,user2,user3"
      LEVEL_TYPE: ${MC_LEVEL_TYPE-DEFAULT}
    ports:
      - 19132:19132/udp
    volumes:
      - /path/to/your/data:/data
    labels:
      minecraft_bedrock_server: "true"
    stdin_open: true
    tty: true
    sysctls:
      net.ipv4.ip_local_port_range: 39132 39133

  minecraft-rest:
    image: macchie/minecraft-bedrock-server-bridge
    container_name: minecraft-rest
    restart: unless-stopped
    depends_on:
      - minecraft-server
    environment:
      - ENABLE_API=true
    ports:
      - 17394:17394
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/log
  
  mosquitto_messages:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_messages
    restart: unless-stopped
    depends_on:
      - mosquitto
    command: "mosquitto_sub -h mosquitto -I message_logger -F '\e[92m%t \e[96m%p\e[0m' -q 0 -t '#'"
        
  logstash:
    build:
      dockerfile: logstash-dockerfile
    container_name: logstash
    restart: unless-stopped
    environment:
      - "LS_JAVA_OPTS=-Xmx1g -Xms1g"
      - "XPACK_MONITORING_ENABLED=false"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
    depends_on:
      - mosquitto

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.9
    container_name: filebeat
    user: root
    restart: unless-stopped
    command: ["filebeat", "-e", "-strict.perms=false"]
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
    depends_on:
      - logstash
      - minecraft-server

  ansible-rulebook:
    build:
      dockerfile: eda-dockerfile
    container_name: ansible-rulebook
    restart: unless-stopped
    depends_on:
      - mosquitto
    volumes:
      - ./eda:/eda
    command: >
      ansible-rulebook
      --rulebook /eda/minecraft-rulebook.yml
      --inventory /eda/inventory.yml
      --source-dir /eda/
      --verbose
